src/Entity/Vol.php
<?php

namespace App\Entity;

use App\Repository\VolRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\UX\Turbo\Attribute\Broadcast;

#[ORM\Entity(repositoryClass: VolRepository::class)]
#[Broadcast]
class Vol
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 6)]
    private ?string $numero_vol = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $depart = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $arrivee = null;

    #[ORM\ManyToOne(inversedBy: 'vols')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Ville $ville_depart = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Ville $ville_arrivee = null;

    #[ORM\Column]
    private ?float $prix = null;

    #[ORM\Column]
    private ?float $reduction = null;

    #[ORM\Column]
    private ?int $nb_places = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumeroVol(): ?string
    {
        return $this->numero_vol;
    }

    public function setNumeroVol(string $nVol): static
    {
        $this->numero_vol = $this->createFlyNumber();

        return $this;
    }

    public function getDepart(): ?\DateTimeInterface
    {
        return $this->depart;
    }

    public function setDepart(\DateTimeInterface $depart): static
    {
        $this->depart = $depart;

        return $this;
    }

    public function getArrivee(): ?\DateTimeInterface
    {
        return $this->arrivee;
    }

    public function setArrivee(\DateTimeInterface $arrivee): static
    {
        $this->arrivee = $arrivee;

        return $this;
    }

    public function getVilleDepart(): ?Ville
    {
        return $this->ville_depart;
    }

    public function setVilleDepart(?Ville $ville_depart): static
    {
        $this->ville_depart = $ville_depart;

        return $this;
    }

    public function getVilleArrivee(): ?Ville
    {
        return $this->ville_arrivee;
    }

    public function setVilleArrivee(?Ville $ville_arrivee): static
    {
        $this->ville_arrivee = $ville_arrivee;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): static
    {
        $this->prix = $prix;

        return $this;
    }

    public function getReduction(): ?float
    {
        return $this->reduction;
    }

    public function setReduction(float $reduction): static
    {
        $this->reduction = $reduction;

        return $this;
    }

    public function getNbPlaces(): ?int
    {
        return $this->nb_places;
    }

    public function setNbPlaces(int $nb_places): static
    {
        $this->nb_places = $nb_places;

        return $this;
    }

    private function createFlyNumber(){
        $ABC = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        $nbs = "0123456789";
        $flyNumber = '';
        $count = 0;
        while($count<6){
            if(strlen($flyNumber)<=1){
                $newIndex = mt_rand(0, 25);
                $str = $ABC;
                
            }
            else{
                $newIndex = mt_rand(0, 9);
                $str = $nbs;
            }
            $newChar = $str[$newIndex];
            $flyNumber .= $newChar;
            $count++;
        }
        return $flyNumber;
    }

    public function __toString(){
        return $this->numero_vol;
    }
}

src/Form/VolType.php
<?php

namespace App\Form;

use App\Entity\Ville;
use App\Entity\Vol;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VolType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('numero_vol')
            ->add('depart')
            ->add('arrivee')
            ->add('prix')
            ->add('reduction')
            ->add('nb_places')
            ->add('ville_depart', EntityType::class, [
                'class' => Ville::class,
'choice_label' => 'nom',
            ])
            ->add('ville_arrivee', EntityType::class, [
                'class' => Ville::class,
'choice_label' => 'nom',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Vol::class,
        ]);
    }
}

src/Controller/VolController.php
<?php

namespace App\Controller;

use App\Entity\Vol;
use App\Entity\Ville;
use App\Form\VolType;
use App\Repository\VolRepository;
use App\Repository\VilleRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;


#[Route('/vol')]
class VolController extends AbstractController
{
    #[Route('/', name: 'app_vol_index', methods: ['GET'])]
    public function index(VolRepository $volRepository, VilleRepository $ville): Response
    {
        return $this->render('vol/index.html.twig', [
            'vols' => $volRepository->findAll(),
            // 'ville' => $ville->findAll(),
        ]);
    }
    
    #[Route('/new', name: 'app_vol_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $vol = new Vol();
        $form = $this->createForm(VolType::class, $vol);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($vol);
            $entityManager->flush();

            return $this->redirectToRoute('app_vol_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('vol/new.html.twig', [
            'vol' => $vol,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_vol_show', methods: ['GET'])]
    public function show(Vol $vol): Response
    {
        return $this->render('vol/show.html.twig', [
            'vol' => $vol,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_vol_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Vol $vol, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(VolType::class, $vol);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_vol_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('vol/edit.html.twig', [
            'vol' => $vol,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/del', name: 'app_vol_delete', methods: ['POST'])]
    public function delete(Request $request, Vol $vol, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$vol->getId(), $request->request->get('_token'))) {
            $entityManager->remove($vol);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_vol_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/vol/_delete_form.html.twig
<form method="post" action="{{ path('app_vol_delete', {'id': vol.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ vol.id) }}">
    <button class="btn">Delete</button>
</form>

templates/vol/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/vol/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Vol{% endblock %}

{% block body %}
    <h1>Edit Vol</h1>

    {{ include('vol/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_vol_index') }}">back to list</a>

    {{ include('vol/_delete_form.html.twig') }}
{% endblock %}

templates/vol/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les vols disponibles{% endblock %}

{% block body %}
    {% include '/includes/header.html.twig' %}
    <h1>Les vols disponibles</h1>
    <main class="main">
        
        {% block main %}
        <div class="display-box">
        <table class="table">
            <thead>
                <tr>
                    {# <th>Id</th> #}
                    <th>Numero de vol</th>
                    <th>Depart</th>
                    <th>Arrivee</th>
                    <th>Ville de départ</th>
                    <th>Ville d'arrivée</th>
                    <th>Prix</th>
                    <th>Reduction</th>
                    <th>Nb_places</th>
                    <th>actions</th>
                </tr>
            </thead>
            <tbody>
            {% for vol in vols %}
                <tr>
                    {# <td>{{ vol.id }}</td> #}
                    <td>{{ vol.numeroVol }}</td>
                    <td>{{ vol.depart ? vol.depart|date('H:i') : '' }}</td>
                    <td>{{ vol.arrivee ? vol.arrivee|date('H:i') : '' }}</td>
                    <td>{{ vol.villeDepart.nom}}</td>
                    <td>{{ vol.villeArrivee.nom}}</td>
                    <td>{{ vol.prix }}</td>
                    <td>{{ vol.reduction }}</td>
                    <td>{{ vol.nbPlaces }}</td>
                    <td>
                        <a href="{{ path('app_vol_show', {'id': vol.id}) }}" class="show"><i class="las la-eye icons" style="transform : scale(1.5, 1.5)"></i></a>                        {% if app.user and "ROLE_ADMIN" in app.user.roles %}
                            <a href="{{ path('app_vol_edit', {'id': vol.id}) }}" class="edit"><i class="las la-pen icons"></i></a>
                        {% endif %}
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="8">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    {% endblock %}
    </main>    
{% endblock %}

templates/vol/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Vol{% endblock %}

{% block body %}
    {% include '/includes/header.html.twig' %}

    <h1>Enregistrer un vol</h1>

    <main class="main">
        {% block main %}
            <div class="display-box" style="text-align: center">
                {{ include('vol/_form.html.twig') }}

            <a href="{{ path('app_vol_index') }}"><i class="las la-backward icons" style="transform: scale(1.5, 1.5)"></i></a>
            </div>
        
        {% endblock %}
    
    </main>

    
{% endblock %}

templates/vol/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Vol{% endblock %}

{% block body %}
    <h1>Vol</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ vol.id }}</td>
            </tr>
            <tr>
                <th>Numero_vol</th>
                <td>{{ vol.numeroVol }}</td>
            </tr>
            <tr>
                <th>Depart</th>
                <td>{{ vol.depart ? vol.depart|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Arrivee</th>
                <td>{{ vol.arrivee ? vol.arrivee|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ vol.prix }}</td>
            </tr>
            <tr>
                <th>Reduction</th>
                <td>{{ vol.reduction }}</td>
            </tr>
            <tr>
                <th>Nb_places</th>
                <td>{{ vol.nbPlaces }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_vol_index') }}">back to list</a>

    <a href="{{ path('app_vol_edit', {'id': vol.id}) }}">edit</a>

    {{ include('vol/_delete_form.html.twig') }}
{% endblock %}